# .pre-commit-config.yaml

repos:
  - repo: https://github.com/psf/black
    rev: '24.4.2'
    hooks:
      - id: black
        name: Black Formatter
        language_version: python3.12 

  - repo: https://github.com/PyCQA/flake8
    rev: '7.1.0'  
    hooks:
      - id: flake8
        name: Flake8 Linter
        additional_dependencies: [flake8-bugbear, flake8-comprehensions]
        language_version: python3.12 

  - repo: https://github.com/pre-commit/mirrors-pylint
    rev: 'v3.0.0a5'
    hooks:
      - id: pylint
        name: Pylint Linter
        language_version: python3.12  
        args: [--max-line-length=88]  # Match Black's line length

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.11.1'  
    hooks:
      - id: mypy
        name: MyPy Type Checker
        language_version: python3.12

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: 'v5.10.1'
    hooks:
      - id: isort
        name: isort Import Sorter
        language_version: python3.12
