name: Deploy to Railway

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Docker (if not already installed)
      run: |
        sudo apt-get update
        sudo apt-get install -y docker.io

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Railway with Docker
      run: |
        echo "${{ secrets.RAILWAY_TOKEN }}" | docker login --username=railway --password-stdin registry.railway.app

    - name: Build and push Docker image to Railway
      env:
        PROJECT_ID: deac629a-f954-4a10-b68b-17efbb6ac790
        IMAGE_NAME: streamlit-quiz-app
      run: |
        docker build -t registry.railway.app/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}:latest .
        docker push registry.railway.app/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}:latest

    - name: Deploy to Railway
      env:
        PROJECT_ID: deac629a-f954-4a10-b68b-17efbb6ac790
      run: |
        curl -H "Authorization: Bearer ${{ secrets.RAILWAY_TOKEN }}" \
        -X POST https://backboard.railway.app/webhook/deploy/${{ env.PROJECT_ID }}
