name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Build: 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo 'export PATH="$HOME/.local/bin:$PATH"' >> $GITHUB_ENV
          poetry --version

      - name: Install all dependencies (including dev)
        run: |
          poetry install

      - name: Run pre-commit hooks
        run: |
          poetry run pre-commit run

      - name: Run tests with pytest
        run: |
          poetry run pytest --cov=src tests/

      - name: Build Docker image
        run: |
          docker build -t my_streamlit_app .

      - name: Run Docker container
        run: |
          docker run -d -p 8501:8501 --name test_app my_streamlit_app

      - name: Test Docker container
        run: |
          for i in {1..10}; do
            curl -f http://localhost:8501 && break
            sleep 2
          done

      - name: Stop Docker container
        run: |
          docker stop test_app
          docker rm test_app

  Deploy:
    runs-on: ubuntu-latest
    needs: Build

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username ${{ secrets.DOCKER_USER }} --password-stdin

    - name: Build and push Docker image to Docker Hub
      env:
        IMAGE_NAME: streamlit-quiz-app
      run: |
        docker build -t ${{ secrets.DOCKER_USER }}/${{ env.IMAGE_NAME }}:latest .
        docker push ${{ secrets.DOCKER_USER }}/${{ env.IMAGE_NAME }}:latest

    - name: Deploy to Railway
      run: |
        curl -H "Authorization: Bearer ${{ secrets.RAILWAY_TOKEN }}" \
        -X POST https://backboard.railway.app/webhook/deploy/${{ secrets.PROJECT_ID }}