name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          docker build -t streamlit-quiz-app .

      - name: Run Docker container
        run: |
          docker run -d -p 8501:8501 --name streamlit-quiz-container streamlit-quiz-app

      - name: Test Docker container
        run: |
          sleep 10  # Wait for the app to start
          curl -f http://localhost:8501  # Check if the app is running

      - name: Run tests inside Docker container
        run: |
          docker exec streamlit-quiz-container poetry run pytest --cov=src tests/

      - name: Stop Docker container
        run: |
          docker stop streamlit-quiz-container
          docker rm streamlit-quiz-container
