name: CI and CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci: 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo 'export PATH="$HOME/.local/bin:$PATH"' >> $GITHUB_ENV
          poetry --version

      - name: Install all dependencies (including dev)
        run: |
          poetry install

      - name: Run pre-commit hooks
        run: |
          poetry run pre-commit run

      - name: Run tests with pytest
        run: |
          poetry run pytest --cov=src tests/

      - name: Build Docker image
        run: |
          docker build -t my_streamlit_app .

      - name: Run Docker container
        run: |
          docker run -d -p 8501:8501 --name test_app my_streamlit_app

      - name: Test Docker container
        run: |
          for i in {1..10}; do
            curl -f http://localhost:8501 && break
            sleep 2
          done

      - name: Stop Docker container
        run: |
          docker stop test_app
          docker rm test_app

  deploy:
    runs-on: ubuntu-latest
    needs: ci

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Railway with Docker
      run: |
        echo "${{ secrets.RAILWAY_TOKEN }}" | docker login --username=railway --password-stdin registry.railway.app

    - name: Build and push Docker image to Railway
      env:
        PROJECT_ID: deac629a-f954-4a10-b68b-17efbb6ac790
        IMAGE_NAME: streamlit-quiz-app
      run: |
        docker build -t registry.railway.app/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}:latest .
        docker push registry.railway.app/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}:latest

    - name: Deploy to Railway
      env:
        PROJECT_ID: deac629a-f954-4a10-b68b-17efbb6ac790
      run: |
        curl -H "Authorization: Bearer ${{ secrets.RAILWAY_TOKEN }}" \
        -X POST https://backboard.railway.app/webhook/deploy/${{ env.PROJECT_ID }}

    - name: Smoke test after deployment
      run: |
        curl -f https://webgame-production.up.railway.app/ || echo "App not reachable!"